// 256 mots français courts, sans accents ni ambiguïté, pour les phrases
// de récupération (8 mots = 64 bits d'entropie — suffisant pour un secret
// vérifié uniquement en ligne, avec rate-limiting côté Supabase).
export const WORDLIST = [
  'abri', 'acier', 'aigle', 'aile', 'amande', 'ambre', 'ancre', 'ange',
  'anneau', 'arbre', 'arc', 'argent', 'arome', 'atlas', 'aube', 'avenir',
  'avion', 'azur', 'bagage', 'balade', 'balcon', 'bambou', 'banane', 'barque',
  'basalte', 'bassin', 'bateau', 'baton', 'belier', 'berge', 'beton', 'bijou',
  'bison', 'blague', 'ble', 'bleu', 'bois', 'bonbon', 'bordure', 'boussole',
  'branche', 'brise', 'brume', 'bulle', 'bureau', 'cabane', 'cactus', 'cadeau',
  'cadre', 'caillou', 'calme', 'camion', 'canard', 'canyon', 'carafe', 'carbone',
  'carte', 'casque', 'castor', 'cave', 'cedre', 'cercle', 'cerise', 'chaine',
  'chaleur', 'chambre', 'chameau', 'champ', 'chanson', 'charbon', 'chariot', 'chat',
  'chemin', 'chene', 'cheval', 'chiffre', 'chocolat', 'ciel', 'cigale', 'cinema',
  'cirque', 'citron', 'climat', 'cloche', 'cobalt', 'coffre', 'colline', 'colonne',
  'comete', 'compas', 'concert', 'condor', 'copain', 'coquille', 'corail', 'corde',
  'costume', 'coton', 'coude', 'couleur', 'courant', 'couronne', 'cousin', 'couteau',
  'crabe', 'craie', 'crayon', 'creme', 'cristal', 'cube', 'cuivre', 'culture',
  'cygne', 'dauphin', 'dent', 'desert', 'dessin', 'destin', 'diamant', 'digue',
  'dindon', 'disque', 'domino', 'dossier', 'douane', 'douche', 'dragon', 'drapeau',
  'duvet', 'echelle', 'eclair', 'ecole', 'ecorce', 'ecran', 'ecume', 'effort',
  'eglise', 'elan', 'enclume', 'encre', 'enfant', 'engin', 'enigme', 'epice',
  'eponge', 'equipe', 'erable', 'escale', 'espace', 'esprit', 'estuaire', 'etage',
  'etoile', 'etude', 'exemple', 'fable', 'falaise', 'famille', 'fanfare', 'farine',
  'faucon', 'fenetre', 'ferme', 'feuille', 'figue', 'filet', 'flamme', 'fleuve',
  'flocon', 'flotte', 'foret', 'fortune', 'fossile', 'foudre', 'fougere', 'four',
  'fourmi', 'fraise', 'fresque', 'fromage', 'fruit', 'fumee', 'fusee', 'galaxie',
  'galet', 'gant', 'garage', 'gazon', 'geant', 'gibier', 'girafe', 'givre',
  'glace', 'gorge', 'goutte', 'graine', 'granit', 'gravier', 'grenier', 'griffe',
  'grotte', 'grue', 'guepard', 'guide', 'guitare', 'hamac', 'hangar', 'herbe',
  'heron', 'hibou', 'histoire', 'hiver', 'horizon', 'hotel', 'huile', 'humide',
  'igloo', 'image', 'iris', 'ivoire', 'jade', 'jaguar', 'jardin', 'jasmin',
  'jetee', 'jeton', 'jouet', 'journal', 'jungle', 'jupiter', 'kayak', 'koala',
  'lagune', 'lampe', 'langue', 'lanterne', 'lapin', 'lavande', 'legende', 'levier',
  'lezard', 'liane', 'lierre', 'lievre', 'lilas', 'lion', 'livre', 'losange',
  'loutre', 'lumiere', 'lune', 'luthier', 'madrier', 'magie', 'maison', 'manoir',
]
